"""Create branches table

Revision ID: 0e0f59970226
Revises: 98473afba903
Create Date: 2025-04-28 21:35:08.530236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0f59970226'
down_revision = '98473afba903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservation_employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_employees',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['usuario.id'], name='reservation_employees_employee_id_fkey'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], name='reservation_employees_reservation_id_fkey'),
    sa.PrimaryKeyConstraint('reservation_id', 'employee_id', name='reservation_employees_pkey')
    )
    op.drop_table('branches')
    # ### end Alembic commands ###
