"""add dismissed to Rating

Revision ID: 209e45e01c6b
Revises: 2ea8c377da3b
Create Date: 2025-04-21 17:41:47.441328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209e45e01c6b'
down_revision = '2ea8c377da3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('dismissed')

    # ### end Alembic commands ###
