"""Ampliar campo password_hash

Revision ID: 390158da4d85
Revises: c05a547fa674
Create Date: 2025-04-24 00:30:14.694368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390158da4d85'
down_revision = 'c05a547fa674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
